package com.yahoo.sdvornik.mem_tables

object FieldName {
  val PRODUCT = "product"
  val DEPARTMENT = "department"
  val LOCATION = "location"
  val INDX = "indx"
  val FLRSET = "flrset"
  val GRADE = "grade"
  val STRCLIMATE = "strclimate"
  val DBTWK_INDX = "dbtwk_indx"
  val INITRCPTWK_INDX = "initrcptwk_indx"
  val ERLSTMKDNWK_INDX = "erlstmkdnwk_indx"
  val EXITDATE_INDX = "exitdate_indx"
  val FCST = "fcst"
  val NUM_SIZES = "num_sizes"
  val TOO = "too"
  val APS_LOWER = "aps_lower"
  val APS = "aps"
  val WOC = "woc"
  val EOH = "eoh"
  val BOD = "bod"
  val CONS = "cons"
  val SBKT = "sbkt"
  val FINAL_VRP = "final_vrp"
  val FINAL_QTY = "final_qty"
}
